# image: xemuliam/dbt:latest

stages:
  - test
  - deploy

before_script:
  - pip install --upgrade pip
  - apt-get update && apt-get install -y python3-venv python3-pip # for Linux runners
  - python3 -m venv env_dbt_demo
  - source env_dbt_demo/bin/activate
  
  - pip install dbt
  - pip install dbt-core==1.6.6
  - pip install dbt-trino==1.6.2
  # - pip install -r requirements.txt # assuming you have a requirements.txt with DBT and other dependencies
  - cd ./dbt_trino_demo
  - dbt deps

test_dbt_models:
  stage: test
  script:
    - dbt debug # Debug DBT models
    - dbt run # Run DBT models
    - dbt test # Run DBT tests
  only:
    - main # or any other branch you want to run tests on

deploy_to_dbt_ec2:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - chmod -R 400 ~/.ssh
    - ssh-keyscan $EC2_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESS 'cd ./ && git pull'
    # - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IPADDRESS 'cd ./ && git pull && dbt run'
  only:
    - main
    