image: fishtownanalytics/dbt:latest

before_script:
  - dbt deps # Install dependencies
  - dbt seed # Load any seed files
  # - pip install dbt-core
  # - pip install dbt-trino

stages:
  - test
  - deploy

test_dbt_models:
  stage: test
  script:
    - dbt debug # Debug DBT models
    - dbt run # Run DBT models
    - dbt test # Run DBT tests
  only:
    - main # or any other branch you want to run tests on

deploy_to_ec2:
  stage: deploy
  script:
    - echo "Deploying to EC2"
    # deployment script
  only:
    - main
