dbt_trino_demo:
  outputs:
    dev:
      type: trino
      method: none   # optional, one of {none | ldap | kerberos}
      user: $DB_TRINO_USER
      password:  # required if method is ldap or kerberos
      catalog: $DB_TRINO_CATALOG
      host: $DB_TRINO_HOST
      port: $DB_TRINO_PORT
      schema: $DB_TRINO_SCHEMA
      threads: 1
  target: dev