dbt_trino_demo:
  outputs:
    dev:
      type: trino
      method: none   # optional, one of {none | ldap | kerberos}
      user: "{{ env_var('DB_TRINO_USER') }}"
      password:  # required if method is ldap or kerberos
      catalog: "{{ env_var('DB_TRINO_CATALOG') }}"
      host: "{{ env_var('DB_TRINO_HOST') }}"
      port: "{{ env_var('DB_TRINO_HOST') | int }}"
      schema: "{{ env_var('DB_TRINO_SCHEMA') }}"
      threads: 1
  target: dev
